msg_board/urls.py
from django.conf.urls import url
from . import views


app_name = 'msg_board'
urlpatterns = [
    #below url is: [domain]/msg_board/
    url(r'^$', views.MessageBoardIndexView.as_view(), name='message_index'),
    url(r'^logout/', views.LogoutView.as_view(), name='logout'),
    url(r'^error_page/(?P<error>[\w\s\.\,]+)/', views.ErrorView.as_view(), name='error_page'),
    url(r'^vote/', views.Board_pollView.as_view(), name='vote'),
    url(r'^create_account/', views.CreateAccountView.as_view(), name='create_account'),
    url(r'^locations/(?P<location>[\w\_]+)/', views.MsgBoardView.as_view(), name='message_board'),
    url(r'^guest_login/(?P<location>[\w\_]+)', views.GuestLoginView.as_view(), name='guest_login'),
]

sessions/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from msg_board import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^msg_board/', include('msg_board.urls')),
    url(r'^accounts/login', views.LoginView.as_view(), name='login_site')
]

msg_board/models.py
from datetime import datetime
from django.db import models


class Location(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        if ' ' in self.name:
            print(
                "Name contains whitespace."
                "Rename this location using the _ character instead of the space character, and then delete the location with the whitespace."
                )
        return self.name.replace("_", " ")


class Msg_post(models.Model):
    username = models.CharField(max_length=30)
    time = models.DateTimeField(auto_now_add=True)
    location = models.ForeignKey(
        'Location',
        on_delete=models.CASCADE,
        max_length=30
        )
    time_of_day = models.CharField(max_length=30)
    quality = models.CharField(max_length=15)
    size = models.CharField(max_length=15)
    #image = models.ImageField()
    comment = models.CharField(max_length=500)

    def __str__(self):
        return self.comment

class Board_choice_poll(models.Model):
    board_choice = models.CharField(max_length=30)

    def __str__(self):
        return self.board_choice

msg_board/forms.py
from django import forms
from django.forms import ModelForm
from msg_board.models import Msg_post, Board_choice_poll
from django.contrib.auth.models import User

TIME_CHOICES = (
    ('Dawn Patrol', 'Dawn Patrol'),
    ('Sunrise', 'Sunrise'),
    ('Morning', 'Morning'),
    ('Lunch Break', 'Lunch Break'),
    ('Afternoon', 'Afternoon'),
    ('Sunset', 'Sunset'),
    ('After Dark', 'After Dark'),
    ('Full Moon', 'Full Moon')
    )
QUALITY_CHOICES = (
    ('Poor', 'Poor'),
    ('Poor+', 'Poor+'),
    ('Poor to Fair', 'Poor to Fair'),
    ('Fair', 'Fair'),
    ('Fair+', 'Fair+'),
    ('Fair to Good', 'Fair to Good'),
    ('Good', 'Good'),
    ('Good+', 'Good+'),
    ('Good to Epic', 'Good to Epic'),
    ('Epic', 'Epic')
    )
SIZE_CHOICES = (
    ('Flat', 'Flat'),
    ('Ankle High', 'Ankle high'),
    ('Knee High', 'Knee high'),
    ('Stomach High', 'Stomach high'),
    ('Chest High', 'Chest high'),
    ('Shoulder High', 'Shoulder high'),
    ('Head High', 'Head high'),
    ('Overhead', 'Overhead'),
    ('Head+1/2', 'Head and a half'),
    ('Double Overhead', 'Double overhead'),
    ('Massive', 'Massive')
    )
BOARD_CHOICES = (
    ('Longboard', 'Longboard'),
    ('Shortboard', 'Shortboard'),
    ('Funboard', 'Funboard'),
    ('Wavestorm', 'Wavestorm'),
    ('Fish', 'Fish'),
    ('Retro', 'Retro'),
    ('Experimental', 'Experimental')
    )

class Msg_boardForm(ModelForm):
    time_of_day = forms.CharField(
        widget=forms.Select(choices=TIME_CHOICES)
        )
    quality = forms.CharField(
        widget=forms.Select(choices=QUALITY_CHOICES)
        )
    size = forms.CharField(
        widget=forms.Select(choices=SIZE_CHOICES)
        )
    comment = forms.CharField(widget=forms.Textarea, strip=True)

    class Meta:
        model = Msg_post
        fields = [
            'time_of_day',
            'quality',
            'size',
            'comment'
        ]


class Board_choice_pollForm(ModelForm):
    board_choice = forms.CharField(
        widget=forms.RadioSelect(choices=BOARD_CHOICES)
        )
    
    class Meta:
        model = Board_choice_poll
        fields = [
            'board_choice'
        ]


class LoginForm(ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'username'}
            )
        )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'placeholder': 'password'}
            )
        )

    class Meta:
        model = User
        fields = [
            'username',
            'password'
            ]


class AccountForm(ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'username'}
            )
        )
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'email'}
            )
        )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'placeholder': 'password'}
            )
        )

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password'
            ]

msg_board/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from msg_board.forms import Msg_boardForm, Board_choice_pollForm, LoginForm, AccountForm
from msg_board.models import Msg_post, Location, Board_choice_poll
from django.views import View
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User


class LoginView(View):
    login_form = LoginForm()

    def get(self, request):
        location = request.GET['next'].lstrip('/msg_board/locations/') #get the raw string of the location only
        return render(request, 'msg_board/login.html', {'location': location, 'login_form': self.login_form})

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            next = request.GET['next']
            return HttpResponseRedirect(next)                
        else:
            message = "Invalid username or password, please try again."
            print(message)
            return HttpResponseRedirect( reverse('msg_board:error_page', args=(message,)) )


class GuestLoginView(View):
    """View used to login as a guest."""

    def get(self, request, location):
        username = 'guest'; password = 'password1234'
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
        else:
            return HttpResponse("Guest login functionality is currently disabled. Please try again later.")
        if request.user.is_authenticated:
            print(request.user.username + " is logged in.")
            if location == 'home':
                return HttpResponseRedirect( reverse('msg_board:message_index') )
        else:
            return render(request, 'msg_board/index.html')
        return HttpResponseRedirect( reverse('msg_board:message_board', args=(location,)) )


class CreateAccountView(View):
    account_form = AccountForm()

    def get(self,request):
        return render(request, 'msg_board/create_account.html', {'account_form': self.account_form})

    def post(self, request):
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        #Need to add validation against the user database here / send the user an email with their info
        user = User.objects.create_user(username, email=email, password=password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            print(user)
        return render(request, 'msg_board/index.html')


class LogoutView(View):

    def get(self, request):
        user = request.user.username
        logout(request)
        if not request.user.is_authenticated:
            print(user + " has logged out.")
        return HttpResponseRedirect( reverse('msg_board:message_index') )


class ErrorView(View):

    def get(self, request, error):
        print(error)
        return render(request, 'msg_board/error.html', {'error_message': error})


class MessageBoardIndexView(View):

    l = Location.objects.all()
    header = 'Post a Session, Read a Session.'
    login_form = LoginForm()
    board_poll_form = Board_choice_pollForm()

    def get(self, request):        
        if request.user.is_authenticated:
            print(request.user.username + " is logged in.")
            login_status = "Welcome back, " + request.user.username + "!"
        else:
            login_status = "Login to post to the message boards."
        return render(
            request,
            'msg_board/index.html',
            {
            'header': self.header,
            'locations': self.l,
            'login_status': login_status,
            'login_form': self.login_form,
            'board_poll_form': self.board_poll_form
            }
            )

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            login_status = "Welcome back, " + user.username +"!"    
        else:
            login_status = "Invalid username and/or password, please try again."
        return render(
                request,
                'msg_board/index.html',
                {
                'login_status': login_status,
                'header': self.header,
                'locations': self.l,
                'board_poll_form': self.board_poll_form
                }
                ) 


class MsgBoardView(LoginRequiredMixin, View):

    def get(self, request, location):
        if request.GET and request.GET['guest'] == 'guest_login':
            username = 'guest'; password = 'password1234'
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
        guest_user = False #initialize this context variable as False so that template renders the msg_form by default
        if request.user.username == 'guest':
            guest_user = True
        msg_form = Msg_boardForm()
        l = Location.objects.get(name=location)
        comment_list = Msg_post.objects.filter(location=l)
        place = l.name.replace('_', ' ')
        return render(
            request,
            'msg_board/msg_board.html',
            {
                'msg_form': msg_form,
                'location': place,
                'comment_list': comment_list,
                'guest_user': guest_user
            }
            )

    def post(self, request, location):
        msg_form = Msg_boardForm()
        if (not request.body) or (len(request.POST['comment'])<4) :
            return HttpResponseRedirect( reverse('msg_board:message_board', args=(location,) ))
        l = Location.objects.get(name=location)
        msg_post = Msg_post(
            username = request.user.username,
            location = l,
            time_of_day = request.POST['time_of_day'],
            quality = request.POST['quality'],
            size = request.POST['size'],
            comment = request.POST['comment']
            )
        msg_post.save()
        comment_list = Msg_post.objects.all()
        return HttpResponseRedirect( reverse('msg_board:message_board', args=(location,) ))


class Board_pollView(View):

    def get_boards(self):
        self.shortboards = Board_choice_poll.objects.filter(board_choice="Shortboard")
        self.number_of_shortboards = len(self.shortboards)
        self.longboards = Board_choice_poll.objects.filter(board_choice="Longboard")
        self.number_of_longboards = len(self.longboards)
        self.fish = Board_choice_poll.objects.filter(board_choice="Fish")
        self.number_of_fish = len(self.fish)
        self.wavestorms = Board_choice_poll.objects.filter(board_choice="Wavestorm")
        self.number_of_wavestorms = len(self.wavestorms)
        self.funboards = Board_choice_poll.objects.filter(board_choice="Funboard")
        self.number_of_funboards = len(self.funboards)
        self.retro = Board_choice_poll.objects.filter(board_choice="Retro")
        self.number_of_retro = len(self.retro)
        self.experimental = Board_choice_poll.objects.filter(board_choice="Experimental")
        self.number_of_experimental = len(self.experimental)

    def post(self, request):
        board_choice_model = Board_choice_poll(
            board_choice = request.POST['board_choice']
        )
        board_choice_model.save()
        return HttpResponseRedirect( reverse('msg_board:message_index') )

    def get(self, request):
        self.get_boards()
        return HttpResponse(
            "Longboards: " + str(self.number_of_longboards) + "\n" +
            "Shortboards: " + str(self.number_of_shortboards) + "\n" +
            "Funboards: " + str(self.number_of_funboards) + "\n" +
            "Wavestorms: " + str(self.number_of_wavestorms) + "\n" +
            "Fish: " + str(self.number_of_fish) + "\n" +
            "Retro: " + str(self.number_of_retro) + "\n" +
            "Experimental: " + str(self.number_of_experimental) + "\n"
            )

msg_board/templates/msg_board/create_account.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<h3>Create a user account.</h3>
<form action="" method="post">{% csrf_token %}
      {{ account_form.as_p }}
      <input type="submit" value="Create account">
</form>

{% endblock content %}

msg_board/templates/msg_board/error.html
{% extends "base.html" %}

{% block content %}

<div>
  {{ error_message }}<br />
  <small><a href="{% url 'login_site' %}">Login</a></small></br />
  <small><a href="{% url 'msg_board:message_index' %}">Back to locations</a></small></br />
</div>

{% endblock content %}

msg_board/templates/msg_board/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h2>{{ header }}</h2><br />
{{ login_status }} <br />

    {% if not request.user.is_authenticated %}

    <form class="login" action="" method="post">{% csrf_token %}
      {{ login_form.as_p }}
      <input type="submit" value="Login" class="submit">
    </form>
    <p>
      <small>
        <a href="{% url 'msg_board:create_account' %}">Create an account</a> |
        <a href="{% url 'msg_board:guest_login' 'home' %}">Continue as a guest</a>
      </small>
    </p>
    {% endif %}

    {% if request.user.is_authenticated %}
    <small><a href="{% url 'msg_board:logout' %}">Logout</a></small><br />
    {% endif %}

{{ error_message }}<br />
{{ http_response }}
<div id="locations">
<h3>Surf spots</h3>
{% for location in locations %}
<a href="{% url 'msg_board:message_board' location.name %}">
  {{ location }}
</a><br />
{% endfor %}
</div>

  <form class="col-2" action="{% url 'msg_board:vote' %}" method="post">
    {% csrf_token %}
    What's your go-to ride?<br />
    {{ board_poll_form.as_p }}
    <button type='submit'>Vote!</button>&nbsp;&nbsp;&nbsp;
    <div class="poll-box"></div>
    <span class="poll-results pointer">View results</span>
  </form>
<br /><br /><br />

<script type="text/javascript">

var xhr = new XMLHttpRequest();
var results; //global variable to store polls results

function getResults() { //replace localhost with domain name in production
xhr.open('GET', 'vote', true);
xhr.onload = function () {
    if (xhr.readyState === xhr.DONE) {
        if (xhr.status === 200) {
            results = xhr.responseText;
        }
    }
};
xhr.send(null);
}
getResults();

function togglePoll() {
  var pollBox = document.querySelector('div.poll-box');
  var resultsSpan = document.querySelector('span.poll-results');
  if (!pollBox.className.includes('data')) {
    getResults();
    pollBox.className = 'poll-box data'; //class is only a flag to allow routine to add innerHTML
    pollBox.innerText = results;
    resultsSpan.innerText = "Hide results";
  } else {
    pollBox.className = 'poll-box';
    pollBox.innerHTML = "";
    resultsSpan.innerText = "View results";
  }
}

document
  .querySelector('.poll-results')
  .addEventListener('click', togglePoll);

$('h2').hide().fadeIn(2500);
</script>
{% endblock content %}

msg_board/templates/msg_board/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div>

<h3>Please login to post to the message boards.</h3>

    {% if not request.user.is_authenticated %}
    <form class="login" action="" method="post">{% csrf_token %}
      {{ login_form.as_p }}
      <input type="submit" value="Login" class="submit">
    </form>
    <p>
    <small><a href="{% url 'msg_board:guest_login' location %}">Continue as a guest</a></small> | 
    {% endif %}
    <small><a href="{% url 'msg_board:message_index' %}">Back to Locations</a></small>
    </p>

  {% if request.user.is_authenticated %}
    <small><a href="{% url 'msg_board:logout' %}">Logout</a></small><br />
    {% endif %}
</div>

{% endblock content %}

msg_board/templates/msg_board/msg_board.html
{% extends "base.html" %}
{% block content %}

<h2>{{ location }}</h2>
<small><a href="{% url 'msg_board:message_index' %}">Back to Locations</a></small><br />
{% if error_message %}
<p>{{ error_message }}</p>
{% endif %}

<div class="col-6">

{% if not guest_user %}
  <form class="comment" action="" method="post"> {% csrf_token %}
  {{ msg_form.as_p }}
  <input type="submit" value="Post it" class="submit">
  </form>
{% endif %}

{% if guest_user %}
  <small>Guests may read posts, but only registered users may post a Session.</small>
{% endif %}

</div>

<div class="col-6">
  <ul>{% for comment in comment_list %}
    <li>
      <small>
        Posted by {{ comment.username }} on {{ comment.time }}
      </small><br />
    <h6>
      {{ comment.size }} | 
      {{ comment.quality }} | 
      {{ comment.time_of_day }} session
    </h6>
    <p class="comment">{{ comment.comment }}</p>
    </li>
    {% endfor %}
  </ul>
</div>

<script type="text/javascript">
  $('h2').hide().fadeIn(1000);
</script>
{% endblock content %}